version: "3.9"

services:
  wireguard:
    image: weejewel/wg-easy:latest
    container_name: wireguard-vpn
    volumes:
      - ~/wg-easy/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "8020:51821"
    environment:
      WG_HOST: ${WG_HOST}
      PASSWORD: ${WG_PASSWORD}
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1